name: deploy-poi

env:
  workingdir: apis/poi/
  repo: devopsoh/api-poi
  context: apis/poi/web
  AZURE_WEBAPP_NAME: openhack5ba15au8poi-staging

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apis/poi/**'
      - '!apis/poi/**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.workingdir}}
    - name: Test
      run: dotnet test ${{ env.workingdir}}/tests/UnitTests/

  deploy-acr-appservice:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to ACR and App Service
        uses: ./.github/actions
        with:
         context: ${{ env.context }}
         repo: ${{ env.repo }}
         registry: ${{ secrets.registry }}
         service_principal: ${{ secrets.service_principal }}
         service_principal_password: ${{ secrets.service_principal_password }}
         AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
         AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}
