name: deploy-userprofile

env:
  workingdir: apis/userprofile/
  repo: devopsoh/api-userprofile
  context: apis/userprofile/

on:
  workflow_dispatch:
  push:
    #branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
      
  acr:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
 
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry }}
          username: ${{ secrets.service_principal }}
          password: ${{ secrets.service_principal_password }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.context }}
          push: true
          tags: ${{ secrets.registry }}/${{ env.repo }}:${{ github.sha }}
