name: deploy-user-java

env:
  workingdir: apis/user-java/
  repo: devopsoh/api-user-java
  context: apis/user-java/
  AZURE_WEBAPP_NAME: openhack5ba15au8poi

on:
  workflow_dispatch:
  push:
    #branches: [ main ]
    #paths:
    #  - 'apis/user-java/**'
    #  - '!apis/user-java/**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ${{ env.workingdir }}

    - name: Run unit tests with Maven
      run: mvn test
      working-directory: ${{ env.workingdir }}

  deploy-acr-appservice:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to ACR and App Service
        uses: ./.github/actions
        with:
         context: ${{ env.context }}
         repo: ${{ env.repo }}
         registry: ${{ secrets.registry }}
         service_principal: ${{ secrets.service_principal }}
         service_principal_password: ${{ secrets.service_principal_password }}
         AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
         AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}