name: deploy-trips

env:
  workingdir: apis/trips/

on:
  workflow_dispatch:
  push:
    #branches: [ api-trips ]
          
jobs:  
  test:  
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2    

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: download dependencies
      run: go get
      working-directory: ${{env.workingdir}}
      
    - name: Test
      run: go test ./tripsgo -run Unit     
      working-directory: ${{env.workingdir}}    
    
  acr:
    runs-on: ubuntu-latest  
    needs: 
    - test
    steps:
    - name: ACR build
      id: acr
      uses: azure/acr-build@v1
      with:
        service_principal: ${{ secrets.service_principal }}
        service_principal_password: ${{ secrets.service_principal_password }}
        tenant: ${{ secrets.tenant }}
        registry: ${{ secrets.registry }}
        repository: ${{ secrets.repository }}
        image: api-trips
        folder: ${{env.workingdir}}
