name: deploy-userprofile

env:
  workingdir: apis/userprofile/
  repo: devopsoh/api-userprofile
  context: apis/userprofile/
  AZURE_WEBAPP_NAME: openhack5ba15au8userprofile/staging

on:
  workflow_dispatch:
  push:
    #branches: [ main ]
    #paths:
     # - 'apis/userprofile/**'
      #- '!apis/userprofile/**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'
        cache-dependency-path: ${{env.workingdir}}
    - run: npm ci
      working-directory: ${{env.workingdir}}
    - run: npm run build --if-present
      working-directory: ${{env.workingdir}}
    - run: npm run test
      working-directory: ${{env.workingdir}}

  deploy-acr-appservice:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to ACR and App Service
        uses: ./.github/actions
        with:
         context: ${{ env.context }}
         repo: ${{ env.repo }}
         registry: ${{ secrets.registry }}
         service_principal: ${{ secrets.service_principal }}
         service_principal_password: ${{ secrets.service_principal_password }}
         AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
         AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}
