name: deploy-trips

env:
  workingdir: apis/trips/
  repo: devopsoh/api-trips
  context: apis/trips
  AZURE_WEBAPP_NAME: openhack5ba15au8trips
  resource_group: openhack5ba15au8rg
  build_name: deploy-poi

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apis/trips/**'
      - '!apis/trips/**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: download dependencies
        run: go get
        working-directory: ${{ env.workingdir }}

      - name: Test
        run: go test ./tripsgo -run Unit
        working-directory: ${{ env.workingdir }}

  deploy-acr-appservice:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to ACR and App Service
        uses: ./.github/actions
        with:
         context: ${{ env.context }}
         repo: ${{ env.repo }}
         registry: ${{ secrets.registry }}
         service_principal: ${{ secrets.service_principal }}
         service_principal_password: ${{ secrets.service_principal_password }}
         AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
         AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}
         resource_group: ${{ env.resource_group }}
         build_name: ${{ env.build_name }}
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
