name: Go

env:
  workingdir: apis/trips/

on:
  push:
    branches: [ api-trips ]
  pull_request:
    branches: [ api-trips ]

jobs:  
  build:  
    runs-on: ubuntu-latest    
    steps:      
    - uses: actions/checkout@v2    

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: download dependencies
      run: go get
      working-directory: ${{env.workingdir}}
      
    - name: Test
      run: go test ./tripsgo -run Unit     
      working-directory: ${{env.workingdir}}
