name: trips-ci

env:
  workingdir: apis/trips/
  build_name: trips-ci

on:
  push:
    branches: [api-trips]
    paths:
      - "apis/trips/**"
      - "!apis/trips/**.md"
  pull_request:
    branches: [api-trips]
    paths:
      - "apis/trips/**"
      - "!apis/trips/**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: download dependencies
        run: go get
        working-directory: ${{env.workingdir}}

      - name: Test
        run: go test ./tripsgo -run Unit
        working-directory: ${{env.workingdir}}

      - uses: actions/github-script@0.9.0
        if: failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
              body: body
            });
